heat_template_version: rocky

description: Simple template to deploy a single compute instance using input parameters

parameters:
  user_key:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
    default: gerardo
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    default: rhel-8.5-x86_64
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    default: m1.medium
  connected2Net:
    type: string
    label: Network name
    description: Name of the network to tonnect the instance
    default: DMZ

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: user_key }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      networks:
        - network: { get_param: connected2Net }
      user_data_format: RAW
      user_data: |
        #cloud-config
        password: SuperSegur0
        chpasswd: {expire: False}
        ssh_pwauth: False
        # Set keyboard layout to "latam"
        runcmd:
          - /usr/bin/localectl set-keymap latam
        # Attach subscription
        rh_subscription:
          activation-key: YOURactivationKEYhere
          org: YOURorganizationID
          auto-attach: True
  my_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: 'Your Provider Network'
  association_instance-fip:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: my_floating_ip }
      port_id: {get_attr: [my_instance, addresses, {get_param: connected2Net}, 0, port]}

outputs:
  instance_ip:
    description: The IP address of the deployed instance
    value: {get_attr: [my_instance, first_address]}
